name: aarch64 Docker image

on:
  push:
    branches: ["main"]
    
permissions:
  packages: write
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: aarch64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Clone PufferPanel src
        uses: actions/checkout@v2
        with:
          repository: PufferPanel/PufferPanel
          path: aarch64/src
    
      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: aarch64
          push: true
          tags: oskardotglobal/pufferpanel:aarch64
